get the object to be translated correctly in Google Translate
plone/plone.app.multilingual pull request #462
Opened 2024-09-29 13:32 UTC by erral

Fixes #303 

It looks like previously the view was executed in the context to be translated, which is not true any more. Now this view is executed in a view traverser like `/es/++addtranslation++2490009c505b4d4b9a030ca631a70a5f` the context (which would be `es` in this case) is usually the parent folder and not the object to be translated. 

The UID in the view traverser (`2490009c505b4d4b9a030ca631a70a5f`) signals the UID of the object to be translated, so we get it via JavaScript and send it to the translation view, which gets the object correctly.

2024-09-29 13:32 UTC, mister-roboto commented
@erral thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-09-29 13:39 UTC, erral commented
@jenkins-plone-org please run jobs

2024-09-29 23:27 UTC, davisagli requested changes

2024-09-29 23:27 UTC, davisagli commented on src/plone/app/multilingual/browser/translate.py
> +                    context = brains[0].getObject()
This is what uuidToObject is for (This is what https://github.com/plone/plone.app.uuid/blob/master/plone/app/uuid/utils.py#L76)

2024-09-30 09:30 UTC, erral commented
@jenkins-plone-org please run jobs

2024-10-02 03:36 UTC, davisagli approved these changes

2024-10-02 03:36 UTC, merged